### ISSUE TITLE
Can't seem to get this working

### ISSUE THREAD

**Issue by vrad-exe** [Armada651/Hydra-OpenVR#2]
As the title says, I'm unable to get this working and can't find any info about what could be wrong. Using the Sixense DLC on its own works fine, though obviously I can't play the maps without a Hydra. If I install the custom DLL from here, the game no longer loads any Sixense-related code and just becomes normal P2. (And prior to the latest Portal 2 update it would simply crash on the loading screen.)

I have heard other people say they got it working, though that was before the latest P2 update which seems to have changed the behavior slightly. There are a couple things I've thought of that might help:
- I have both of my Portal 2 installations on my D: drive, so maybe that's causing problems? The installation instructions do specifically say to put it at the default path on C:.
- I can download an old version of the game using Depot Downloader, and see if that works any better.

But both of these things would take quite a bit of effort and aren't really something I want to do unless I know it will help. Any suggestions? Are you even active anymore?

**Comment by CakeLancelot** [comment]
By normal Portal 2, do you mean the splash screen and the Sixsense Perpetual Motion Pack logo on the title are also not present?

Haven't really run into this issue myself if so, all you should need to do is make sure the DLC is enabled in the Steam Library and the DLL is in the right place. I would recommend [v0.2](https://github.com/CrossVR/Hydra-OpenVR/releases/tag/v0.2), as the initial release doesn't have support for buttons and seems to be a bit buggier.

**Comment by vrad-exe** [comment]
I am using v0.2. It doesn't fully revert to normal Portal 2; from what I can tell, the Sixense *assets* still get loaded, but the *code* doesn't. So the splash screen still appears because that's defined in a text file, but the motionpack logo is missing, the Sixense settings menu is broken, etc.

I just went ahead and downloaded a January 2017 version of P2. I'll post here if it works with that.

**Comment by vrad-exe** [comment]
Nope, still crashes with the custom DLL in a 2017 build of the game located at the default install location. Is there anything else I need to install for it to work? I have SteamVR, and even tried installing the Hydra drivers (though it was crashing before that).

**Comment by CakeLancelot** [comment]
Did you start SteamVR prior to launching Portal 2? You'll have to uncheck "Use Desktop Game Theatre while SteamVR is active" in the launch properties of P2.

**Comment by vrad-exe** [comment]
I did that with the 2017 build and it worked! It did not work with the current version however, so it looks like people will need to download an old version of the game if they want to use this. The July 2020 update or earlier should work, I know of someone who got it working on that version. Thanks for the help.

**Comment by CakeLancelot** [comment]
That's odd, given I have the latest update installed and it works fine. Perhaps it only works because I have some leftover files from the previous versions of the game? I'll let you know if I can reproduce the issue you describe - it's good that it at least works on an older version though.

**Comment by vrad-exe** [comment]
Huh, that's interesting, I just managed to reproduce the "only Sixense assets loading" thing in my old copy of the game. So that seems to not actually be tied to the version like I thought, I'm going to do some testing in my main installation.

**Comment by vrad-exe** [comment]
And now I got the custom DLL to work in the current version of the game. Huh.
